DROP DATABASE eleve;
CREATE DATABASE eleve;

USE eleve;

CREATE TABLE professeur (
code_prof INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(100),
prenom VARCHAR(100)
);
CREATE TABLE eleve (
code_eleve INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
nom VARCHAR(50), 
prenom VARCHAR(50)
);

CREATE TABLE uv (
code_uv INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
nom VARCHAR(50),
annee DATE,
code_prof INTEGER NOT NULL,
FOREIGN KEY(code_prof) REFERENCES professeur(code_prof) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE A_Suivi (
code_eleve INTEGER NOT NULL,
code_uv INTEGER NOT NULL,
FOREIGN KEY(code_eleve) REFERENCES eleve(code_eleve) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (code_uv) REFERENCES uv(code_uv) ON DELETE RESTRICT ON UPDATE CASCADE,
PRIMARY KEY (code_eleve, code_uv),
Note INTEGER,
Annee DATE
);

